---
title: "Correlação não é causalidade, e daí?"
author: ""
date: ""
output: 
  html_document:
    highlight: espresso
    theme: spacelab
---
#### [Mário Rutman](http://lattes.cnpq.br/4148568651932363)
#### `r format(Sys.Date(), '%d-%b-%Y')`. 

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```
## {.tabset .tabset-pills}
### __1. Objetivo.__

#### Tenho visto em _lives_, em cursos de Estatística e de Análise de Dados a afirmação de que 'correlação não é causalidade', indicando que algo falta à correlação, como se estivesse incompleta sem a causalidade. Penso que o fato de uma análise de correlação não ter revelado ou encontrado causas não a torna deficiente.

#### Minha argumentação será no sentido de mostrar que um estudo de correlação não tem necessariamente que  identificar ou referir-se à causalidade. Para defender meu entendimento abordarei três pontos: i) buscar causas é tarefa totalmente diferente de analisar correlações, são instâncias heterogêneas; ii) sob certa perspectiva é possível buscar correlações sem dar qualquer importância à causalidade; e, iii) a noção de causa e efeito, embora irresistível, não passa de um hábito sem fundamento.

#### Para tratar do tema apresentarei resumidamente alguns conceitos filosóficos úteis.

#### Toda a discussão irá girar em torno do conhecimento por indução. Esta maneira de conceber o que é conhecimento foi adota pelos chamados filósofos empiristas. Como preparação vou expor em linhas gerais a teoria do conhecimento de pensadores considerados racionalistas, que não acreditavam que a experiência poderia levar ao conhecimento. 

#### Vou usar o termo __causa__ como sinônimo de motivo, razão ou princípio, tal como no uso diário de nossa língua. A causa de algo é sua razão, o seu motivo, seu porquê, o que a explica, sua origem e princípio.

#### Adotarei como base de análise sobre empirismo o excelente "Iniciação à História da Filosofia" de Danilo Marcondes.^[Marcondes, Danilo. __Iniciação à Historia de Filosofia__. Rio de Janeiro: Jorge Zahar Ed., 1998.]

### __2. Correlação e causalidade: domínios diferentes.__

#### A ideia de causalidade surge já nos primeiros filósofos quando criaram alguns conceitos para responder qual seria a causa da causa da causa... até a causa primeira de todas que chamavam de _arqué_. Para Tales de Mileto era a água, para Anaxímenes era o ar, Anaximandro o [_apeiron_ (sem limites)](https://pt.wikipedia.org/wiki/Anaximandro#A_cosmologia_de_Anaximandro), Demócrito o átomo etc.

#### Conhecer cientificamente __$B$__ é saber inequivocamente tudo que causa __$B$__, seu porquê. __Platão__ chama este tipo de conhecimento de [_episteme_](https://pt.wikipedia.org/wiki/Epistemologia). É o saber permanente contraposto à variabilidade das opinões, que mudam na mesma medida que se alteram os objetos captados pelos sentidos. Estes nos afastam do conhecimento, só a razão isolada de todos os sentidos pode conhecer. 

#### Em linha com as ideias de morte e reencarnação do [Orfismo](https://pt.wikipedia.org/wiki/Orfismo_(culto)#Vida_ap%C3%B3s_a_morte), __Platão__ explica que a alma após a morte, sem as atribulações que o corpo demanda, no [mundo das ideias](https://pt.wikipedia.org/wiki/Teoria_das_ideias),  tudo conhece com os olhos do espírito ([_nous_](https://pt.wikipedia.org/wiki/Nous)). Para este filósofo a alma encarnada nada conhece de novo, apenas relembra uma coisa ou outra no mar do esquecimento ([_lethe_](https://en.wikipedia.org/wiki/Lethe)) em que vive. 

#### É impensável para Platão que o conhecimento tenha alguma relação com a análise de um conjunto de observaçãoes ou experimento. A valorização de Matemática em sua filosofia é em razão de seu caráter abstrato, da distância que esta disciplina mantém em relação aos sentidos. 

#### __Aristóteles__ entende que o que existe são as coisas individuais (não as formas ou essências em um mundo à parte como Platão), este cavalo, esta mesa.  E será o intelecto, por meio da abstração, que irá depreender a essência das coisas particulares. São as essências que fazem algo ser o que é, e não outra coisa, o que faz com que isto seja um cavalo e não uma mesa. Para o Estagirita, o que causa este cavalo específico é a essência de cavalo que 'está' nele. 

#### Este pensador considera que a experiência tem algum valor ("Nada está no intelecto sem antes ter passado pelos sentidos") no processo de conhecimento, mas é apenas uma referência, o conhecimento é resultado do trabalho do intelecto que, por abstração, alcança as essências. 

#### Para [__Descartes__](https://pt.wikipedia.org/wiki/Ren%C3%A9_Descartes) conhecer __$B$__ é resultado da impossibilidade de duvidar __racionalmente__ de __$B$__. 

#### Segundo o filósofo francês, a razão ('igualmente partilhada por todos') com suas operações, partindo princípios auto evidentes e os encadeando sem deixar espaço para dúvida em cada etapa do raciocínio, conhece verdadeiramente tudo que causa __$B$__. Esta [forma de conhecer](https://pt.wikipedia.org/wiki/Discurso_sobre_o_M%C3%A9todo#Os_quatro_preceitos) foi inspirada na Matemática. 

|                   "...rejeitamos todos conhecimentos somente prováveis, e declaramos que se 
|                   deve confiar apenas nas coisas perfeitamentes conhecidas e das quais 
|                   não se pode duvidar [...] podemos obter opiniões prováveis, mas não a 
|                   ciência perfeita [...] só a Aritmética e a Geometria estavam isentas de 
|                   todo defeito de falsidade ou de incerteza [...] É preciso notar, além disso,
|                   que as experiências acerca das coisas são muitas vezes enganosas [...] 
|                   De tais considerações infere-se claramente porque é que a Aritmética e a 
|                   Geometria são muito mais certas que as outras disciplinas: são efectivamente
|                   as únicas que lidam com um objeto tão puro e simples que não têm de fazer 
|                   suposição alguma que a experiência torne incerta..."^[Descartes, René. __Regras para a Direcção do Espírito (Regra II)__. Lisboa: Edições 70, s/d, pgs 14 a 17.]

#### Segundo __Descartes__ conhecer é conduzir a razão à moda da Matemática, isto é rejeitar o provável e as experiências enganosas, e considerar somente aquilo de que é impossível duvidar.

#### Vemos assim que a produção do conhecimento, a determinação de causas, é tarefa intelectual, exercício da razão, não é decorrência de observações, medidas e cálculos.  

#### A experiência, um estudo de correlação, pode até __inspirar__ o intelecto do cientista a criar uma teoria que revelará uma relação de causalidade, tal como se diz que a queda da maçã levou [Isaac Newton](https://pt.wikipedia.org/wiki/Isaac_Newton#A_queda_da_ma%C3%A7%C3%A3_e_a_d%C3%BAvida_de_Newton) a estabelecer a Teoria da Gravitação. Mas o que demonstra causas é tarefa exclusivamente racional de criação e articulação de conceitos. A [teoria](https://pt.wikipedia.org/wiki/Teoria), o encontro com as causas, não emerge naturalmente de uma coleção de experiências, tal como a radiografia de uma coxa mostra o fêmur.

#### Num estudo de correlação coletam-se as observações, identificam-se as variáveis e estuda-se __quanto__ estas se correlacionam. A forma de se obter o grau de uma correlação é bastante engenhosa, mas é medição e contagem, não é atividade especulativa ou teórica. Neste cenário, não há como surgir afirmação __fundamentada__ de que __$A$__ causa __$B$__.

#### Assim, é por meio da razão que se chega à causa, à explicação. Só o intelecto articula conceitos, princípios e definições para reunir a diversidade das observações e dados sob uma mesma ordem, para então determinar causas. Apresentar causas e fazer correlações são trabalhos diferentes, especialidades distintas. 

>#### Assim, correlação não é, nem pode, nem deve ser causalidade.

#### __Obs.__ No cotidiano da produção científica, correlação e causalidade vêm confundidas, pois o cientista já tem em mente alguns candidatos à causa e se orienta pelas observações para adicionar outros, é a fase de colecionar hipóteses. O pesquisador pode __depois__, usando ferramentas para calcular a correlação entre variaveis, verificar quais hipóteses devem continuar sendo trabalhadas, para ao final, a(s) selecionada(s) se apresentar(em) como causa. Note que é uma [conta de chegada](https://www.contabilidade-financeira.com/2007/04/conta-de-chegada.html), na prática o cientista após idas e vindas, muitos erros, acertos na hora errada e equívocos oportunos apresenta uma explicação numa teoria, mas esta explicação não é produto da correlação.  

### __3. Causalidade: esse assunto não me interessa.__

#### Quer um analista de dados reflita ou não sobre o tema do conhecimento, seu comportamento pressupõe uma determinada concepção sobre _o que é_ conhecer e _como_ se conhece. Considerando que a base de seu trabalho é coleta e análise de observações, ele é um __empirista__, uma vez que para esta corrente de pensamento a experiência é guia e critério de validade do conhecimento e a __indução__ o modo de obtê-lo.

#### Não é possível apontar um analista de dados tomando o conhecimento como reminiscência do que a alma '_viu_' no mundo das idéias, tal como Platão entendia, nem como Descartes concebia, visto que toda medida contém um erro e as análises estatísticas são sempre da ordem do provável, nunca do indubitável. Um analista de dados que negasse o valor da experiência estaria pondo em questão a própria função que exerce.  

#### Um estudo de correlação numa análise de dados é uma etapa de uma experiência. Coletam-se as observações, identificam-se as variáveis e estuda-se __quanto__ estas se correlacionam. Assim, o analista de dados será sempre um empirista. Vejamos então com mais detalhe o que é o __empirismo__. 


####
|                   "Em linhas gerais, "empirismo" significa uma posição filosófica que toma
|                   a experiência como como guia e critério de validade de suas afirmações,
|                   sobretudo nos campos da teoria do conhecimento e da filosofia da ciência.
|                   O termo é derivado do grego _empeiria_, significando basicamente uma forma 
|                   de saber derivado da experiência sensível e de dados acumulados com base nessa
|                   experiência, permitindo a realização de fins práticos."^[Id, 1998, pg. 176.]

#### Para [Francis Bacon](https://en.wikipedia.org/wiki/Francis_Bacon) o conhecimento científico se processa pelo método indutivo. A partir de uma coleção de observações infere-se uma relação entre elas. Os fenômenos ocorridos num conjunto de observações são generalizados. Tal extrapolação pressupõe uma [uniformidade](https://en.wikipedia.org/wiki/David_Hume#Induction_and_causation) (Princípio da Uniformidade ou Semelhança ou Princípio da Uniformidade da Natureza) entre o que já foi observado e o que não foi. 

|                  "Geralmente pensamos que as observações que fazemos são capazes de justificar
|                  algumas expectativas ou previsões sobre observações que ainda não fizemos,
|                  bem como afirmações gerais que vão além do observado. Por exemplo, a observação
|                  de que o pão de certa aparência tem sido nutritivo até agora parece justificar a
|                  expectativa de que o próximo pedaço de pão semelhante que como também seja nutritivo,
|                  tal qual a alegação de que o pão desse tipo geralmente é nutritivo. Essas inferências
|                  do observado para o não observado, ou para leis gerais, são conhecidas como
|                  “inferências indutivas”. [O Problema da Indução](https://plato.stanford.edu/entries/induction-problem/#HumeProb).

#### Este princípio que sustenta a indução é um problema. Adotá-lo significa usar algo sem fundamento: o que garante esta uniformidade? Por outro lado negá-lo impossibilita o próprio conhecimento, posto que as observações tornar-se-iam um conjunto de casos aleatórios e desconexos. Assim, o empirismo vem sempre acompanhado de um nível de [ceticismo](https://en.wikipedia.org/wiki/Skepticism), seja ele moderado ou radical.

#### O ceticismo em [John Locke](https://en.wikipedia.org/wiki/John_Locke) é moderado, pois admite o tipo de conhecimento dedutivo, tal como o da matemática, mas o obtido pela observação e experiência é relativo, daí chamá-lo de crença ou opinião.

|                   "Locke afirma que não podemos conhecer as coisas em sua essência; portanto sobre
|                   o mundo natural temos apenas crenças opiniões,  mas não conhecimento verdadeiro
|                   (_true knowledge_). Sob esse aspecto Locke pode ser considerado um cético moderado.
|                   O conhecimento demonstrativo é aquele derivado da nossa percepção da relação entre
|                   nossas idéias, restringindo-se a campos do saber como a Geometria. Podemos 
|                   assim ter um conhecimento demonstrativo ou dedutivo que não é derivado da experiência,
|                   mas da observação do modo de operar da mente.Este conhecimento (_knowledge_) é certo e 
|                   definitivo e se distingue do conhecimento derivado das percepções sensíveis que 
|                   Locke de denomina "crença" ou "opinião" (_belief_) e que é relativa essa experiência."^[Ibd. pg. 181.]

#### __Locke__ admite o conhecimento procedente dos sentidos e da experiência, embora reconheça sua natureza contingencial. Seu ceticismo moderado tem um caráter antiespeculativo, prático, uma vez que não se detém diante do que não compreende. A tomada de decisão não pode esperar pelo completo conhecimento verdadeiro das causas, por uma teoria estabelecida. O filósofo observa: 

|                    "É de grande utilidade para o marinheiro saber a extensão de sua sonda, 
|                    embora não possa com ela medir toda a profundidade do oceano. É conveniente que saiba
|                    que ela é suficientemente longa para alcançar o fundo dos lugares necessários para
|                    orientar sua viagem, e preveni-lo de esbarrar contra recifes que podem destruí-lo.[...]
|                    Não nos diz respeito conhecer todas as coisas, mas apenas as que se referem à nossa
|                    conduta. Se pudermos descobrir aquelas medidas por meio das quais uma criatura racional,
|                    posta nesta situação do homem no mundo, pode e deve dirigir suas opiniões e ações delas
|                    dependentes, não devemos nos molestar por que outras coisas escapam ao nosso conhecimento”.^[John Locke, Ensaio sobre o entendimento humano, tr. Eduardo Abranches de Soveral. Lisboa: Fundação Calouste Gulbenkian, 1999, p. 26.]

#### O 'homem no mundo' não pode esperar o conhecimento se completar para agir. Suponhamos um analista de dados que pense como __Locke__ e após seus estudos tivesse descoberto uma correlação de 90% entre __$A$__ e __$B$__, mas que não houvesse nada em __$A$__ que pudesse ser chamado de __causa__ de __$B$__. Ele lamentaria sua situação? Claro que não. É o que tem hoje e encontrar a verdadeira causa de __$B$__ pode ser bastante demorado. 

#### A _contrario sensu_, imaginemos que um ganhador do Prêmio Nobel tenha descoberto que __$C$__ é a __causa__ de __$B$__, mas nosso analista observou que seu grau de correlaçao é de 70%, portanto menor que o entre __$A$__ e __$B$__ (90%). Qual usaria para fazer prognósticos? Considerando que o referido analista segue a filosofia de _Locke_, que não tem veleidades metafísicas, usaria __$A$__.

#### Se um investidor observa uma correlação de 90% entre __$DCDD$__ ('dia em que está com dor de dente') e a valorização de seus ativos naquele dia é de 70% entre __$APDO$__ ('aumento da procura e diminuição da oferta') com o mesmo resultado, ele poderá sem qualquer problema de consciência optar por __$DCDD$__ para tomar decisões quanto a seus ativos^[Evidentemente um analista de mercado profissional, que administre o patrimônio de terceiros, jamais poderá dizer isso.]. O objetivo prático de uma alta correlação entre variáveis desconsidera qualquer necessidade ou referência a alguma causa.

#### Pelos motivos acima, se um tal analista de dados fosse questionado quanto ao fato de que 'correlação não é causalidade', diria que não vê importância nem tem interesse no tema. 

### __4. Causalidade: ficção da mente.__ 

#### [__David Hume__](https://en.wikipedia.org/wiki/David_Hume), o mais radical dos empiristas coloca em xeque o próprio conceito de causalidade.

|                   "Hume questiona a realidade objetiva desse princípio causal. De fato,
|                   se observarmos, no exemplo famoso, o movimento das bolas de bilhar em uma mesa,
|                   tudo o que vemos é o impacto do taco sobre a primeira bola e,
|                   por sua vez o impacto da primeira sobre a segunda, 
|                   mas a causalidade propriamente dita não pode ser observada. Tudo o que a
|                   a experiência nos revela é uma conjunção constante entre fenômenos,
|                   e não uma conexão necessária que chamamos de causalidade."^[Ibd. pg. 182.]

#### O filósofo escocês considera a causalidade uma ilusão, uma força do hábito que adquirimos ao ver repetidamente grupos coisas semelhantes seguidas por outros grupos de coisas semelhantes, que nada mais é que correlação. A relação de causa e efeito não está na natureza, nas coisas nem na razão, é apenas repetida conjugação de fenômenos.

|                   "Objetos semelhantes sempre se encontram em conexão com objetos semelhantes.
|                   Disso temos experiência. De acordo com essa experiência podemos definir uma
|                   causa como objeto seguido de outro, de tal forma que todos os objetos semelhantes
|                   ao primeiro são seguidos de objetos semelhantes ao segundo. Ou, em outros termos,
|                   tal que, se o primeiro objeto não existisse, o segundo também não existiria.
|                   O aparecimento de uma causa, sempre traz à mente, por uma transição costumeira,
|                   a idéia de efeito. Disso também temos experiência. Podemos, assim, conforme essa
|                   experiência, formular uma outra definição de causa que chamaríamos de um objeto
|                   seguido de outro, e cuja aparição sempre conduz o pensamento a idéia desse outro objeto.(_Investigação sobre o Entendimento Humano_, séc. XVII)"^[Ibd. pg. 183.]

#### O prof. Danilo Marcondes resume:

|                   "Para Hume, portanto, a causalidade resulta apenas de uma regularidade ou repetição
|                   em nossa experiência de uma conjunção constante entre fenômenos que,
|                   por força do hábito, acabamos por projetar na realidade, tratando-a como se fosse algo
|                   existente. É nesse sentido que pode ser dito que a causalidade é uma forma nossa de
|                   perceber o real, uma ideia derivada da reflexão sobre as operações de nossa própria
|                   mente,  e não uma conexão necessária entre causa é efeito, uma característica
|                   do mundo natural."^[Ibd. pg. 183.]

#### A ideia de causalidade é basilar na Ciência e na Filosofia, colocá-la em questão é suspeitar da possibilidade de conhecimento, revela radical ceticismo. A argumentação de __Hume__ é de tal forma pertinente que [Kant](https://pt.wikipedia.org/wiki/Immanuel_Kant), em seu _Prolêgomenos_, afirmou que "a leitura de Hume despertou-me de meu sonho dogmático".

#### A ligação necessária entre fenômenos que denominamos causalidade é uma ficção mental. Observamos grupos de repetições e inferimos que esta relgularidade vem dos objetos que compõem estes grupos. Isso que chamamos de causalidade é uma mania de nossa _psiquê_.

#### Não existindo causalidade no sentido de ligação necessária, o que temos de objetivo, que é produto da experiência, é a correlação. Desse modo, não apenas não falta causalidade à correlação, como é o __máximo__ que se tem quando se deseja relacionar conjuntos de variáveis.

#### Para um analista de dados que adote a visão de mundo de Hume só existem correlações que acertam muitas previsões ou erram muitas, fortes ou fracas, esclarecedoras ou desorientadoras, que ele queira ou não 'apostar suas fichas'. Não há qualquer causa subjacente que ordene a relação entre as observações.

### __5. Conclusão.__

#### Se você é um cientista de dados e sua investigação de correlação foi questionada por não ser 'causalidade', pode responder que admira o trabalho especulativo-científico, mas que sua tarefa é encontrar padrões sem fazer inferências sobre seu estatuto metafísico.

#### Pode refutá-lo, afirmando que não tem qualquer interesse no assunto 'causalidade', que é 'um homem no mundo', que não pode esperar o conhecimento das causas para decidir, que troca sem pesar o conhecimento das profundezas do oceano pela certeza de que seu navio não será destruído pelos arrecifes.

#### Sugeriria ainda, dizer a quem o interpela que 'causalidade' é apenas um costume, um hábito irresistível. Lembrando que nada está por baixo de uma correlação a controlá-la, a grenciá-la. 

#### Por fim, ofereça um café a quem veio indagá-lo sobre faltar 'causalidade' em sua correlação e diga que sabia que viria tratar do tema, pois sua pesquisa indicou que há forte correlação entre as variáveis __$MUC$__ ('mostrar uma correlação') e __$AADCNC$__ ('aparecer alguém dizendo que correlação não é causalidade').

